name: pm_course
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - notebook=6.4.10
  - pandas=1.4.2
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - keras=2.10.0
  - tensorflow=2.10.0
  - numpy=1.19.5
  - xgboost=1.5.1